config/routes.rb
ProjetoExemplo05::Application.routes.draw do
  
  resources :users

  root to: "portal#index"
  post "/authentication" => "portal#login"
  match "/panel" => "portal#panel"
  match "/end_session" => "portal#end_session"
  match "/access_denied" => "portal#access_denied"

end

app/models/user.rb
class User < ActiveRecord::Base  
  #include BCrypt  
  attr_accessible :active, :name, :password, :username, :password_confirmation
  attr_accessor :password_confirmation
  
  before_save do |user|
    user.username.downcase!
    user.active = true
    user.password =  Digest::MD5.hexdigest(password)
  end

  validates :name, presence: true
  validates :username, presence: true, 
                       uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_authentication, acceptance: {accept: true}

  def password_authentication
    self.password == self.password_confirmation
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/portal_controller.rb
class PortalController < ApplicationController
  include ApplicationHelper
  
  before_filter except: [:index, :login, :access_denied] do
    redirect_to access_denied_path unless authenticated?
  end

  before_filter only: [:index] do
    redirect_to panel_path if authenticated?
  end

  def index
    @user = User.new
  end

  def login
    @user = User.new(params[:user])

    respond_to do |format|
      if authentication(@user)
        format.html {redirect_to panel_path }
      else
        format.html {redirect_to root_path, notice: 'Login fail!' }
      end
    end
  end

  def end_session
    logout
    redirect_to root_path
  end

  def panel
  end

  def access_denied
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_filter except: [:new, :create, :show] do
    redirect_to access_denied_path unless authenticated?
  end

  before_filter except: [:index] do
    redirect_to root_path if authenticated?
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def authentication(current_user)
    user = User.find_by_username(current_user.username.downcase)
    unless user.nil?
      if Digest::MD5.hexdigest(current_user.password) == user.password
        session[:user] = current_user
      end
    else
      return false
    end  
  end

  def logout
    session[:user] = nil
  end

  def authenticated?
    session[:user]
  end

end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse">
	<div class="navbar navbar-inner">
		<%= link_to 'Authentication App', root_path, class: 'brand' %>
		<div class="container">
			<ul class="nav">
				<li><%= link_to 'Login', root_path %></li>
				<li><%= link_to 'Sign Up', new_user_path %></li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_navbar_authenticated.html.erb
<div class="navbar navbar-inverse">
	<div class="navbar navbar-inner">
		<%= link_to 'Authentication App', root_path, class: 'brand' %>
		<div class="container">
			<ul class="nav">
				<li><%= link_to 'Users', users_path %></li>
				<li><%= link_to 'Sign Out', end_session_path %></li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjetoExemplo05</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if authenticated? %>
	<%= render "layouts/navbar_authenticated" %>
<% else %>
	<%= render 'layouts/navbar' %>
<% end %>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/portal/access_denied.html.erb
<div class="alert alert-error">
	<h1>Access denied!</h1>
</div>

app/views/portal/index.html.erb
<h1>Bem-vindo</h1>

<%= form_for @user, url: authentication_path do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username, autofocus: "autofocus" %> <br>
	<%= f.label :password %>
	<%= f.password_field :password %> <br>
	<%= f.submit 'Sign in', class: 'btn' %>
	<%= link_to 'Sing Up', new_user_path, class: 'btn' %>
<% end %>

<% unless notice.nil? %>
<div class="alert alert-error">
	<h1 id="notice"><%= notice %></h1>
</div>
<% end %>

app/views/portal/panel.html.erb
<h1>Wellcome!</h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %> <br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Sign up!', class: 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-bordered table-hover">
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Password</th>
    <th>Active</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.active %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Account created successfully!</h1>
<%= link_to 'Back to home page', root_path %>